name: densenet-161

params:
  _target_: timm.create_model
  pretrained: true
  model_name: densenet161.tv_in1k
  num_classes: 10

training:
  epochs: 1
  early_stopping: true
  save_path: "densenet161_best_model.pt"
  device: cuda:1
  patience: 10
  min_delta: 0.0