name: seresnext-50

params:
  _target_: timm.create_model
  pretrained: true
  model_name: seresnext50_32x4d.gluon_in1k
  num_classes: 10

training:
  epochs: 1
  early_stopping: true
  save_path: "seresnext50_best_model.pt"
  device: cuda:1
  patience: 10
  min_delta: 0.0 