name: squeezenet-1_1

params:
  _target_: models.SqueezeNet_1_1_Custom
  weights: SqueezeNet1_1_Weights.IMAGENET1K_V1
  num_classes: 10

training:
  epochs: 5
  early_stopping: true
  save_path: "squeezenet1_1_best_model.pt"
  device: cuda:1
  patience: 10
  min_delta: 0.0