train_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: true
  num_workers: 4

val_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: false
  num_workers: 4